Sources/CodeScanner/CodeScanner.swift

Solved an error when running on device: 
`Overriding instance method must be as accessible as its enclosing type`

Making inherited functions and variables public

---

Sources/CodeScanner/CodeScanner.swift

Currently CodeScanner only works correctly if your device (or app) is locked to portrait. If your app needs to use another orientation it won't show correctly. This allows it to launch with another orientation (for me it mattered when using an iPad in portrait), and allows you to rotate even when the view is visible.

Alternate orientation and rotation support

---

.gitignore
Sources/CodeScanner/CodeScanner.swift

Fixes a bug where the camera preview may not be visible for several seconds after returning from a child view. The main change is to move the preview implementation to viewWillAppear rather than in viewDidAppear. Also removed redundant logic for starting the capture session. In addition, implemented scan modes, once, oncePerCode and continuous.

Scan modes, bug fix

---

Sources/CodeScanner/CodeScanner.swift

This is a fix for #11 where the video capture session restarts and the preview layer is reloaded because pulling down a sheet partially (not completely) fires `viewWillDisappear` and `viewDidAppear`.
I made the following changes:
1. Added a nil check to `viewDidAppear` to avoid redundant preview layer instantiation
2. Changed `viewWillDisappear` into `viewDidDisappear` so that the capture session won't stop until the sheet is completely pulled down and closed

Avoid redundant reload when sheet is pulled down

---

Sources/CodeScanner/CodeScanner.swift

I think the behavior that playing a vibration after found the code is out of the scope of this library. It's impossible to customize such as using haptic notification or beep sound.
I met this problem during to use to make our production app. 
In specific, I want to use `UINotificationFeedbackGenerator#notificationOccurred(.success)` after found the code, not the vibration which is too heavy and uncomfortable feedback.
CodeScanner already has a grate point to handle this: `completion: @escaping (Result<String, ScanError>) -> Void`.
The users can add their own logic in completion handler, so it's now more flexible.

Remove vibration playing after found the code

---

Package.swift
Sources/CodeScanner/CodeScanner.swift

In beta 3, linking to Swift Packages using APIs normally unavailable to application extensions now results in a build error: cf https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes#Swift-Packages
This PR addresses the issue by replacing the use of `UIApplication.shared` (which is indeed unavailable to app extensions) with a view controller API.

Fix build for Xcode 13 beta 3

---

Sources/CodeScanner/CodeScanner.swift

When the CodeScannerView is used in a navigation stack, if you navigate
*back* to it it will no longer scan any codes (because
isFinishedScanning is true). This changes it so that we reset the state
of the ScannerController when the view apepars, so that it's ready to
be reused.

Reset the ScannerController on viewWillAppear

---

Sources/CodeScanner/CodeScanner.swift

After using this library in my project I found out, that there is currently no way to detect if the user has not granted permissions to the camera. This results in only a black screen for the CodeScannerView.
This PR adds an error case for missing rights, so the developer can update the UI to inform the user about the missing right. This might not be the cleanest implementation as it will always return the missingRights error for every error that occurred during initialization of init of `AVCaptureDeviceInput`. It works well for my case so far and is a purely additive change.
Do you mind merging this and releasing a new version @twostraws ? It has been a while since 1.0.7 and quite some new features were added (like viewfinder support)...

Add missing rights check

---

Package.swift
Sources/CodeScanner/CodeScanner.swift

Fixes #33.
This adds macOS 11 as a platform (== macCatalyst v14.0), which prevents linking failures, and marks the classes as available from macCatalyst 14.0+ which prevents compile failures.
A `#available` directive cannot be used, as a swift package is compiled and linked regardless of the importing project's target SDK.

Add support for use with macOS Catalyst (14.0+)

---

Sources/CodeScanner/ScannerViewController.swift

Currently we fail only with `.permissionDenied` after requesting camera access (and not getting any). If camera access is already denied the error is swallowed.

Proper permission denied error if camera access is denied

---

Sources/CodeScanner/CodeScanner.swift
Sources/CodeScanner/ScannerViewController.swift

Autofocus on devices that are equipped with an Ultra Wide Camera seems to be off using the default Camera. This is why we select the Ultra Wide Camera per default now.
Fixes #89

[#89] Use the Ultra WIde Camera per default if available

---

Sources/CodeScanner/ScannerViewController.swift

found each QR code separately in manual mode for 2 or more QR in one picture

found each QR code separately in manual mode

---

Sources/CodeScanner/CodeScanner.swift
Sources/CodeScanner/ScannerViewController.swift

So we can draw a cool shape around the tracked code.

Result returns corners of scanned code.

---

Sources/CodeScanner/ScannerViewController.swift

The value of `isGalleryShowing` is not updated when the gallery is dismissed with a swipe down (instead of tapping on cancel). If the gallery is dismissed in such fashion the delegate method `imagePickerControllerDidCancel` is not called and therefore the value is not updated. This causes some strange behaviour when trying to present for the second time.
Fixes #67

Fix galery boolean for swipe down dismiss

---

Sources/CodeScanner/ScannerViewController.swift

Fixes an issue where the CaptureSession became unresponsive while the torch was on or where the CaptureSession wouldn't properly start at all when the torch was on by default.
Fixes #85

fix: #85 unreliable torch

---

README.md
Sources/CodeScanner/AVCaptureDevice+bestForBuiltInCamera.swift

Due to different minimum focus distance built in modern cameras it is hard to focus on small barcodes. To improve the fucus it is needed to apply appropriate zoom factor.
Based on sample code from Apple [AVCamBarcode: Detecting barcodes and faces](https://developer.apple.com/documentation/avfoundation/capture_setup/avcambarcode_detecting_barcodes_and_faces) `AVCaptureDevice#setRecommendedZoomFactor(forMinimumCodeSize:)` method was added to set required zoom factor for desired code size.
Additionaly, `AVCaptureDevice.zoomedCameraForQRCode(withMinimumCodeSize:)` method was added to choose single wide angle camera and apply zoom factor at once. From my experiments, the focus is a lot better on devices with dual or tripple cameras while scanning codes from short distance.
More information can …

[#89] [#113] [#124] Focus improvements on dual and tripple cameras

---

Sources/CodeScanner/ScannerViewController.swift

Minor code clean up to keep related codebase together

Separate delegates into extensions

---

Sources/CodeScanner/CodeScanner.swift
Sources/CodeScanner/ScannerViewController.swift

Barcode scanning apps could benefit from performance gains of skipping taking photos if they don't really need those pictures

Ability to skip taking a photo if it's not required

---

Sources/CodeScanner/CodeScanner.swift
Sources/CodeScanner/ScannerViewController.swift

Problem statement:
When scanning the same barcode again (either right away or after scanning another product) - could be done by continuous option, but the handler would be called each time which could be undesirable (for example, presenting a sheet when a code is detected). Using oncePerCode kind of does the trick, but scanning the same code again doesn't work as the name suggests.
Solution:
Ability to recognize any barcode except the specific "ignored" list which could let us put the current barcode into the ignored list and once another code is detected we update the list (like a "dynamic oncePerCode")

Ability to continuously scan by ignoring specific codes

---

Sources/CodeScanner/CodeScanner.swift
Sources/CodeScanner/ScannerViewController.swift

If a user is taking an action with the result of the scanned barcode and in the meantime the app recognizes another barcode then the user's progress could be lost, hence the need for the ability to pause.
Also minor improvements:
- `final class`
- `guard let captureSession = captureSession else` -> `guard let captureSession else`

Ability to pause scanning (i.e. when presenting)

---

Sources/CodeScanner/PrivacyInfo.xcprivacy

Since the app doesn't track or use users' information, I added this default privacy manifest file to prevent Apple warnings

Add privacy manifest file

---

Package.swift
Sources/CodeScanner/CodeScanner.swift
Sources/CodeScanner/ScannerViewController.swift

- Improved code readability
- Removed macOS target since it doesn't compile

Improvement of code readability

---

.github/workflows/build.yml
Package.swift
Sources/CodeScanner/AVCaptureDevice+bestForBuiltInCamera.swift
Sources/CodeScanner/CodeScanner.swift
Sources/CodeScanner/ScannerViewController.swift

I'm working on a new app that is available on all Apple platforms. But only on iOS I want to use this library to securely transfer some credentials from the Mac app to the iPhone app. But due to limitations in SwiftPM or Xcodes build system, it's not possible to include this package to a multi-platform project and just to link it when building for iOS. I'd need to create multiple targets to do that, which I don't want to do as it's a SwiftUI app and I like to keep things simple & clean.
This PR adds building support for other Apple platforms by specifying compatibility in the Package manifest while basically commenting out all code when those platforms are targeted during a build.
I'd understand if you don't want to merge this. But I needed it, so I figured maybe others may need it as …

Add support for adding this lib to multi-platform targets

---

Sources/CodeScanner/ScannerViewController.swift

- Ensures that the application properly handles cases where no features are found, preventing silent failures.
- Removes the use of force casting, improving code safety and reliability.

Fix error handling when no features are found and remove force casting

---

Sources/CodeScanner/ScannerViewController.swift

This change solves a fix I was able to reproduce consistency by denying access to the camera when prompted.
I have verified the fix (i.e. the crash does not happen anymore).
Stack trace of the crash I was experiencing:
```
Crashed: com.apple.coremedia.capture.tccserver
0  libdispatch.dylib              0x64d8 _dispatch_assert_queue_fail + 120
1  libdispatch.dylib              0x6460 _dispatch_assert_queue_fail + 194
2  libswift_Concurrency.dylib     0x62b58 swift_task_isCurrentExecutorImpl(swift::SerialExecutorRef) + 284
3  [redacted]                     0x5239f4 closure #2 in closure #1 in [redacted].body.getter + 4373346804 (<stdin>:4373346804)
4  [redacted]                     0x6030ac closure #1 in CodeScannerView.ScannerViewController.requestCameraAccess(completion:) + 428 …
```

Dispatch failure on main queue to prevent crash
